config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contactus' => 'pages#contactus'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </head>

  <body>
        <%# Navigation Bar %>
        

          <nav class="navbar navbar-inverse navbar-toggleable-sm bg-inverse navbar-expand">
            <div class="container">
              <%= link_to "Ruby on Rails", root_path, class: "navbar-brand" %>
              <ul class="nav navbar-nav">
                <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
                <li class="nav-item"><%= link_to "Contact", contactus_path, class: "nav-link" %></li>
              </ul>
            </div>
          </nav>

    <%= yield %>

    <%# Footer %>
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>@Copyright 2023 Hammad Ahmad</p>
        </center>
        </div>
        </footer>
  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>We are professionals helping the business to grow with digital services</p>
        </div>
    </div>

app/views/pages/contactus.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>Contact us</h1>
        <p>Contact us at www.hammadahmad.com</p>
        </div>
</div>

app/views/pages/home.html.erb
<div class=" jumbotron jumbotron-home" >
    <div class="container">
    <h1>Welcome to my website!</h1>
            <p>This Is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pleces of content. Use it as a starting point to create something more unique. </p> 
            <%= link_to "Learn more", class: "btn btn-primary btn-ig" %>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading 1</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
            <p><%= link_to "View details", "#", class:"btn btn-secondary"%></p>
        </div>
        
        <div class="col-md-4">
            <h2>Heading 2</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
            <p><%= link_to "View details", "#", class:"btn btn-secondary"%></p>
        </div>
        
        <div class="col-md-4">
            <h2>Heading 3</h2>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
            <p><%= link_to "View details", "#", class:"btn btn-secondary"%></p>
        </div>
    </div>
</div>